# Site settings
title: 钇钛网——郭宇翔的博客
email: yourtion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yourtion
github_username:  yourtion

# Build settings
markdown: kramdown

# permalink
permalink: /:title.html
JB :
  version : 0.3.0
  
  comments :
      provider : duoshuo
      duoshuo :
        short_name : yourtion
