# Site settings
title: 钇钛网
subtitle: 郭宇翔的博客
description: Yourtion's Blog
url: https://blog.yourtion.com
# cdn_url : http://yblog.b0.upaiyun.com
encoding: utf-8

author:
  name: Yourtion
  img: yourtion.jpg
  picture: /assets/img/yourtion.jpg
  about: 一只喜欢各种折腾的程序猴
  email: yourtion@gmail.com
  github: yourtion
  twitter: yourtion
  facebook: yourtion
  linkedin: yourtion

# permalink
permalink: /:title.html

# Build settings
safe: false
timezone: Asia/Shanghai
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji
exclude:
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
feed:
  path: atom.xml

paginate: 5
paginate_path: "/page/:num"

sass:
  style: compressed

analytics:
  provider: google_baidu
  baidu: "46fcc15011207e116bc3aa85d8a3811e"
  google: "UA-12599330-12"
  # sensors: "https://track.fc.umer.im/track/sa?project=yblog"
