# Site settings
title: 钇钛网
subtitle: 郭宇翔的博客
description: Yourtion's Blog
production_url : http://blog.yourtion.com
cdn_url : http://yblog.b0.upaiyun.com
encoding: utf-8

author :
  name : Yourtion
  email : yourtion@gmail.com
  github : yourtion
  twitter : yourtion

# Build settings
safe: false
markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
syntax-highlighting:
  enabled : false
gems:
  - jekyll-sitemap

# permalink
permalink: /:title.html

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false
  IMAGE_PATH : false

  categories_path : /categories.html
  tags_path : /tags.html
  guestbook_path : /guestbook.html
  about_path : /about.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : duoshuo
    duoshuo :
      short_name : yourtion
      top_threads_num : 5
      top_threads_range : monthly

  analytics :
    provider : google_baidu
    baidu :
      tracking_id : 'c172b7087a2b6b62acb6057bb733a8ea'
    google :
      tracking_id : 'UA-12599330-12'
