# Site settings
title: 钇钛网
subtitle: 郭宇翔的博客
description: Yourtion's Blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
encoding: utf-8

author :
  name : yourtion
  email : yourtion@gmail.com
  github : yourtion
  twitter : yourtion

# Build settings
markdown: rdiscount
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
syntax-highlighting:
  enabled : false
# permalink
permalink: /:title.html

safe: false
production_url : http://blog.yourtion.com
cdn_url : http://7x2vxl.com1.z0.glb.clouddn.com

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false
  IMAGE_PATH : false

  categories_path : /categories.html
  tags_path : /tags.html
  guestbook_path : /guestbook.html
  about_path : /about.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  categorie_list: ["iOS","Android"]
  tag_list: ["MongoDB","Android"]

  comments :
    provider : duoshuo
    duoshuo :
      short_name : yourtion

  analytics :
    provider : google
    baidu :
      tracking_id : '1'
    google :
      tracking_id : '2'
