# Site settings
title: 钇钛网——郭宇翔的博客
email: yourtion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yourtion
github_username:  yourtion

# Build settings
markdown: kramdown

# permalink
permalink: /:title.html

safe: false
production_url : http://blog.yourtion.com
cdn_url : http://yourtion.u.qiniudn.com

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false
  IMAGE_PATH : false

  # categories_path : /categories.html
  # tags_path : /tags.html
  # atom_path : /atom.xml
  # rss_path : /rss.xml

  comments :
    provider : duoshuo
    duoshuo :
      short_name : yourtion

  analytics :
    provider : google
    baidu :
      tracking_id : '1'
    google :
      tracking_id : '2'
